It’s a Python-based scientific computing package targeted at two sets of audiences:

* A replacement for NumPy to use the power of GPUs
* a deep learning research platform that provides maximum flexibility and speed

In [4]:
from __future__ import print_function
import torch
from torch import tensor

In [6]:
x=torch.empty(5,3) # uninitialized matrix ::: An uninitialized matrix is declared, 
#but does not contain definite known values before it is used. 
#When an uninitialized matrix is created, whatever values were in the 
#allocated memory at the time will appear as the initial values.

In [4]:
x

tensor([[1.3452e-43, 0.0000e+00, 0.0000e+00],
        [9.2196e-41, 0.0000e+00, 6.3369e-10],
        [1.6744e+01, 4.5695e-41, 6.7787e+02],
        [4.5695e-41, 1.4013e-45, 1.3563e-19],
        [0.0000e+00, 0.0000e+00, 2.5038e-12]])

Construct a randomly initialized matrix:

In [7]:
x = torch.rand(5,3)

In [8]:
x

tensor([[0.0231, 0.5859, 0.5752],
        [0.9910, 0.4907, 0.1230],
        [0.8141, 0.0651, 0.0208],
        [0.5304, 0.4169, 0.0039],
        [0.1583, 0.1971, 0.4755]])

Construct a matrix filled zeros and of dtype long:



In [9]:
x = torch.zeros(5,3, dtype=torch.long)

In [10]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

Construct a tensor directly from data:



In [11]:
x = torch.tensor([5.5,3])

In [13]:
print(x)

tensor([5.5000, 3.0000])


 create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [14]:
x = x.new_ones(5,3,dtype=torch.double)

In [15]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [16]:
x.size() # tuple; 

torch.Size([5, 3])

In [20]:
y = torch.rand(5,3, dtype=torch.double)

In [21]:
x+y

tensor([[1.9682, 1.7363, 1.6636],
        [1.3013, 1.1209, 1.3198],
        [1.8179, 1.9675, 1.0693],
        [1.3366, 1.1058, 1.5476],
        [1.4892, 1.1419, 1.7941]], dtype=torch.float64)

In [22]:
torch.add(x,y)

tensor([[1.9682, 1.7363, 1.6636],
        [1.3013, 1.1209, 1.3198],
        [1.8179, 1.9675, 1.0693],
        [1.3366, 1.1058, 1.5476],
        [1.4892, 1.1419, 1.7941]], dtype=torch.float64)

In [25]:
result = torch.empty(5, 5, dtype=torch.double)
torch.add(x, y, out=result)

tensor([[1.9682, 1.7363, 1.6636],
        [1.3013, 1.1209, 1.3198],
        [1.8179, 1.9675, 1.0693],
        [1.3366, 1.1058, 1.5476],
        [1.4892, 1.1419, 1.7941]], dtype=torch.float64)

In [26]:
result

tensor([[1.9682, 1.7363, 1.6636],
        [1.3013, 1.1209, 1.3198],
        [1.8179, 1.9675, 1.0693],
        [1.3366, 1.1058, 1.5476],
        [1.4892, 1.1419, 1.7941]], dtype=torch.float64)

In [27]:
result.size()

torch.Size([5, 3])

adding in place

In [28]:
y.add_(x)

tensor([[1.9682, 1.7363, 1.6636],
        [1.3013, 1.1209, 1.3198],
        [1.8179, 1.9675, 1.0693],
        [1.3366, 1.1058, 1.5476],
        [1.4892, 1.1419, 1.7941]], dtype=torch.float64)

In [29]:
y

tensor([[1.9682, 1.7363, 1.6636],
        [1.3013, 1.1209, 1.3198],
        [1.8179, 1.9675, 1.0693],
        [1.3366, 1.1058, 1.5476],
        [1.4892, 1.1419, 1.7941]], dtype=torch.float64)

In [30]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [31]:
x[:,1]

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [32]:
y[:,1]

tensor([1.7363, 1.1209, 1.9675, 1.1058, 1.1419], dtype=torch.float64)

In [33]:
y

tensor([[1.9682, 1.7363, 1.6636],
        [1.3013, 1.1209, 1.3198],
        [1.8179, 1.9675, 1.0693],
        [1.3366, 1.1058, 1.5476],
        [1.4892, 1.1419, 1.7941]], dtype=torch.float64)

Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [34]:
x=torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) ## the size -1 is inferred from other dimensions
x.size(),y.size(),z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [35]:
y

tensor([ 0.7654, -0.2217,  1.3426,  0.3877,  0.7625,  0.1751,  1.3141, -0.8600,
        -1.4175,  1.5221,  0.6412,  0.3400, -1.7938, -0.2927,  0.0341, -0.8786])

In [36]:
z

tensor([[ 0.7654, -0.2217,  1.3426,  0.3877,  0.7625,  0.1751,  1.3141, -0.8600],
        [-1.4175,  1.5221,  0.6412,  0.3400, -1.7938, -0.2927,  0.0341, -0.8786]])

If you have a one element tensor, use .item() to get the value as a Python number



In [38]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5539])
0.5538854598999023


Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [39]:
a = torch.ones(5)
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [2]:
import numpy as np
a= np.ones(5)
b = torch.from_numpy(a)

In [3]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [18]:
c , c1 = map(tensor, (a,a))

In [19]:
c,c.shape,c1,c1.shape

(tensor([1., 1., 1., 1., 1.], dtype=torch.float64),
 torch.Size([5]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64),
 torch.Size([5]))

CUDA tensors

In [42]:
torch.cuda.is_available()

True

In [44]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.5539], device='cuda:0')
tensor([1.5539], dtype=torch.float64)
